### PR TITLE
Py3 and Ckan 2.9 support

### PR DESCRIPTION
**Pull request by peterVorman**

### CODE REVIEW

**Review by jguo144 — APPROVED** [review]
LGTM

**Review by jguo144 — CHANGES_REQUESTED** [review]
On second thought it would better to use the constant `IS_CKAN_29_OR_HIGHER` instead of `six.PY3` consistently.

**Review by Andretalik — APPROVED** [review]
LGTM!

**Review by jguo144 — APPROVED** [review]
LGTM

**Pull request merged**
